apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clone-of-my-pvc-1
spec:
  storageClassName: my-sc-1
  dataSource:
    name: my-pvc-1
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
